import { useState, useEffect } from "react";
import { useMutation, useQueryClient, useQuery } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { z } from "zod";
import { apiRequest } from "@/lib/queryClient";
import { FileUpload } from "./file-upload";
import { PropertySelector } from "./property-selector";
import { useToast } from "@/hooks/use-toast";
import { type Property } from "@shared/schema";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Checkbox } from "@/components/ui/checkbox";
import { Form, FormControl, FormField, FormItem, FormLabel, FormMessage } from "@/components/ui/form";
import { X } from "lucide-react";

const createRfpSchema = z.object({
  property: z.string().min(1, "Property is required"),
  tenantName: z.string().min(1, "Tenant name is required"),
  projectName: z.string().min(1, "Project name is required"),
  confidential: z.boolean().default(false),
  sentBy: z.string().min(1, "Sent by is required"),
  sentOn: z.string().min(1, "Sent on date is required"),
  developmentContact: z.string().optional(),
  projectArea: z.string().optional(),
  requestTypes: z.array(z.string()).min(1, "At least one request type is required"),
  notes: z.string().optional(),
});

type CreateRfpFormData = z.infer<typeof createRfpSchema>;

interface CreateRfpModalProps {
  isOpen: boolean;
  onClose: () => void;
}

export function CreateRfpModal({ isOpen, onClose }: CreateRfpModalProps) {
  const [selectedFiles, setSelectedFiles] = useState<File[]>([]);
  const { toast } = useToast();
  const queryClient = useQueryClient();

  // Fetch properties to get property details for project name generation
  const { data: properties = [] } = useQuery<Property[]>({
    queryKey: ["/api/properties"],
  });

  const form = useForm<CreateRfpFormData>({
    resolver: zodResolver(createRfpSchema),
    defaultValues: {
      property: "",
      tenantName: "",
      projectName: "",
      confidential: false,
      sentBy: "",
      sentOn: new Date().toISOString().split('T')[0],
      developmentContact: "",
      projectArea: "",
      requestTypes: [],
      notes: "",
    },
  });

  // Watch specific form fields to auto-generate project name in real-time
  const watchProperty = form.watch("property");
  const watchTenantName = form.watch("tenantName");
  const watchConfidential = form.watch("confidential");
  
  useEffect(() => {
    if (watchProperty && properties.length > 0) {
      const selectedProperty = properties.find(p => p.id.toString() === watchProperty);
      
      if (selectedProperty) {
        const propertyDisplay = `${selectedProperty.propertyName} - ${selectedProperty.building}`;
        
        let autoGeneratedName = "";
        if (watchConfidential) {
          autoGeneratedName = `Confidential @ ${propertyDisplay}`;
        } else if (watchTenantName?.trim()) {
          autoGeneratedName = `${watchTenantName.trim()} @ ${propertyDisplay}`;
        } else {
          autoGeneratedName = `@ ${propertyDisplay}`;
        }
        
        // Auto-populate the project name field (user can still edit it)
        form.setValue('projectName', autoGeneratedName, { shouldValidate: false });
      }
    }
  }, [watchProperty, watchTenantName, watchConfidential, properties, form]);

  const createMutation = useMutation({
    mutationFn: async (data: CreateRfpFormData) => {
      if (selectedFiles.length > 0) {
        // If files are present, use FormData
        const formData = new FormData();
        
        // Add form fields
        formData.append('property', data.property);
        formData.append('tenantName', data.tenantName);
        formData.append('projectName', data.projectName);
        formData.append('confidential', data.confidential.toString());
        formData.append('sentBy', data.sentBy);
        formData.append('sentOn', data.sentOn);
        formData.append('developmentContact', data.developmentContact || '');
        formData.append('projectArea', data.projectArea || '');
        formData.append('requestTypes', JSON.stringify(data.requestTypes));
        formData.append('notes', data.notes || '');

        // Add files
        selectedFiles.forEach((file) => {
          formData.append('files', file);
        });

        return apiRequest("/api/rfp-requests/with-files", "POST", formData);
      } else {
        // No files, send JSON data
        return apiRequest("/api/rfp-requests", "POST", data);
      }
    },
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["/api/rfp-requests"] });
      queryClient.invalidateQueries({ queryKey: ["/api/rfp-requests/stats"] });
      toast({
        title: "RFP Created",
        description: "The RFP has been created successfully",
      });
      form.reset();
      setSelectedFiles([]);
      onClose();
    },
    onError: (error: any) => {
      toast({
        title: "Error",
        description: error.message || "Failed to create RFP",
        variant: "destructive",
      });
    },
  });

  const onSubmit = (data: CreateRfpFormData) => {
    createMutation.mutate(data);
  };

  const handleRequestTypeChange = (requestType: string, checked: boolean) => {
    const currentTypes = form.getValues('requestTypes');
    if (checked) {
      form.setValue('requestTypes', [...currentTypes, requestType]);
    } else {
      form.setValue('requestTypes', currentTypes.filter(type => type !== requestType));
    }
  };

  const handleClose = () => {
    form.reset();
    setSelectedFiles([]);
    onClose();
  };

  return (
    <Dialog open={isOpen} onOpenChange={handleClose}>
      <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle>Create New RFP</DialogTitle>
          <DialogDescription>
            Enter the initial RFP information to begin the workflow process
          </DialogDescription>
        </DialogHeader>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            {/* Basic Information */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium text-gray-900 border-b pb-2">Basic Information</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="property"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Property *</FormLabel>
                      <FormControl>
                        <PropertySelector
                          value={field.value}
                          onChange={field.onChange}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="tenantName"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Tenant Name *</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder="Tenant or client name"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="projectName"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Project Name *</FormLabel>
                    <FormControl>
                      <Input 
                        placeholder="Project name (auto-generated, editable)"
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="sentBy"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Sent By *</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder="Person who sent the RFP"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="sentOn"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Sent On *</FormLabel>
                      <FormControl>
                        <Input 
                          type="date"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                <FormField
                  control={form.control}
                  name="developmentContact"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Development Contact</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder="Development team contact"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="projectArea"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Project Area</FormLabel>
                      <FormControl>
                        <Input 
                          placeholder="e.g., 10,000 sq ft"
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </div>

              <FormField
                control={form.control}
                name="confidential"
                render={({ field }) => (
                  <FormItem className="flex flex-row items-start space-x-3 space-y-0">
                    <FormControl>
                      <Checkbox
                        checked={field.value}
                        onCheckedChange={field.onChange}
                      />
                    </FormControl>
                    <div className="space-y-1 leading-none">
                      <FormLabel>
                        Confidential Project
                      </FormLabel>
                      <p className="text-sm text-muted-foreground">
                        Mark this project as confidential
                      </p>
                    </div>
                  </FormItem>
                )}
              />
            </div>

            {/* Request Types */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium text-gray-900 border-b pb-2">Request Type *</h3>
              
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                {['Pricing', 'Schedule', 'Space Plan'].map((type) => (
                  <div key={type} className="flex items-center space-x-2">
                    <Checkbox
                      id={type}
                      checked={form.watch('requestTypes').includes(type.toLowerCase().replace(' ', '-'))}
                      onCheckedChange={(checked) => 
                        handleRequestTypeChange(type.toLowerCase().replace(' ', '-'), checked as boolean)
                      }
                    />
                    <label 
                      htmlFor={type}
                      className="text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70"
                    >
                      {type}
                    </label>
                  </div>
                ))}
              </div>
              {form.formState.errors.requestTypes && (
                <p className="text-sm font-medium text-destructive">
                  {form.formState.errors.requestTypes.message}
                </p>
              )}
            </div>

            {/* Notes */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium text-gray-900 border-b pb-2">Additional Information</h3>
              
              <FormField
                control={form.control}
                name="notes"
                render={({ field }) => (
                  <FormItem>
                    <FormLabel>Notes</FormLabel>
                    <FormControl>
                      <Textarea 
                        placeholder="Any additional notes or special requirements"
                        rows={3}
                        {...field}
                      />
                    </FormControl>
                    <FormMessage />
                  </FormItem>
                )}
              />
            </div>

            {/* File Upload */}
            <div className="space-y-4">
              <h3 className="text-lg font-medium text-gray-900 border-b pb-2">Files</h3>
              
              <FileUpload
                onFilesSelected={setSelectedFiles}
                multiple={true}
                accept=".pdf,.doc,.docx,.xls,.xlsx,.jpg,.jpeg,.png"
                maxSize={10 * 1024 * 1024} // 10MB
                className="w-full"
              />
              
              {selectedFiles.length > 0 && (
                <div className="space-y-2">
                  <p className="text-sm font-medium">Selected Files:</p>
                  <ul className="text-sm text-gray-600 space-y-1">
                    {selectedFiles.map((file, index) => (
                      <li key={index} className="flex justify-between items-center">
                        <span>{file.name}</span>
                        <button
                          type="button"
                          onClick={() => setSelectedFiles(files => files.filter((_, i) => i !== index))}
                          className="text-red-500 hover:text-red-700"
                        >
                          <X className="h-4 w-4" />
                        </button>
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>

            {/* Action Buttons */}
            <div className="flex justify-end space-x-3 pt-6 border-t">
              <Button type="button" variant="outline" onClick={handleClose}>
                Cancel
              </Button>
              <Button 
                type="submit" 
                disabled={createMutation.isPending}
              >
                {createMutation.isPending ? "Creating..." : "Create RFP"}
              </Button>
            </div>
          </form>
        </Form>
      </DialogContent>
    </Dialog>
  );
}